export type Language = 'fr' | 'en';
export interface Item { title: string; body: string }
export interface Copy {
  nav: string[]; eyebrow: string; headline: string[]; intro: string; heroBody: string;
  call: string; discover: string; reassurance: string; metrics: Item[];
  painLabel: string; painTitle: string; painIntro: string; pains: Item[];
  humanLabel: string; humanTitle: string; humanBody: string[]; quote: string;
  howLabel: string; howTitle: string; steps: Item[];
  whereLabel: string; whereTitle: string; whereIntro: string; services: Item[];
  resultsTitle: string; results: string[]; faqLabel: string; faqTitle: string; faqs: Item[];
  contactLabel: string; contactTitle: string; contactBody: string; booking: string;
  bookingNote: string; footer: string; rights: string; motion: string; menu: string;
}
export const copy: Record<Language, Copy> = {
  fr: {
    nav: ["Ce qu’on fait", 'Comment ça marche', 'Où on aide', 'Questions'],
    eyebrow: 'L’intelligence artificielle. Le bon sens en plus.',
    headline: ['MOINS DE TÂCHES.', 'PLUS DE TEMPS.', 'PLUS DE POSSIBILITÉS.'],
    intro: 'Nous optimisons votre entreprise en vous faisant gagner du temps et de l’argent.',
    heroBody: 'On regarde ce qui vous ralentit et on installe des outils simples qui font le travail plate à votre place. Vos employés gardent leur job. Ils retrouvent leur temps.',
    call: 'Réserver un appel gratuit', discover: 'Voir comment ça marche',
    reassurance: 'Aucune connaissance technique requise. Partout au Canada, à distance ou chez vous.',
    metrics: [{title:'Votre équipe',body:'Toujours au cœur de l’entreprise'}, {title:'Moins de routine',body:'Plus de place pour le vrai travail'}, {title:'Premier appel gratuit',body:'Pour savoir si on peut vous aider'}, {title:'Partout au Canada',body:'À distance ou chez vous'}],
    painLabel:'ÇA VOUS RESSEMBLE?', painTitle:'L’IA est complexe.\nVotre quotidien ne devrait pas l’être.',
    painIntro:'Vous n’avez pas besoin de comprendre l’intelligence artificielle. Vous voulez optimiser vos départements sans devenir un technicien informatique.',
    pains:[
      {title:'« On répond toujours aux mêmes courriels. »',body:'On installe un système qui répond correctement, tout de suite, et qui envoie les vrais cas à une personne.'},
      {title:'« Je découvre mes chiffres trop tard. »',body:'On vous fait un écran simple qui montre ce qui se passe aujourd’hui dans votre entreprise, pas le mois passé.'},
      {title:'« Mes bons employés sont pris dans la paperasse. »',body:'On enlève la paperasse de leur bureau pour qu’ils fassent le travail pour lequel vous les avez engagés.'},
      {title:'« J’ai peur que ce soit compliqué et que ça plante. »',body:'Vous ne touchez à rien de technique. On l’installe, on forme vos employés, et on reste là après.'}
    ],
    humanLabel:'LA TECHNOLOGIE AU SERVICE DES GENS', humanTitle:'Même équipe.\nNouvel élan.',
    humanBody:['On n’est pas là pour remplacer vos employés. On est là pour leur redonner du temps.', 'Recopier des informations, courir après les factures, remplir le même formulaire pour la centième fois : c’est ce travail-là qu’on confie à l’IA.', 'Vos employés font ensuite ce que l’IA ne peut pas faire : parler aux clients, prendre des décisions, faire grandir l’entreprise. Même équipe, plus d’ouvrage de fait, moins d’épuisement.'],
    quote:'« Si un employé fait ça depuis 20 ans à la main, ce n’est pas lui le problème. C’est la tâche. »',
    howLabel:'COMMENT ÇA MARCHE', howTitle:'Quatre étapes.\nAucune surprise.',
    steps:[{title:'On écoute.',body:'On passe du temps dans votre entreprise et on trouve ce qui vous ralentit vraiment. Cette étape est gratuite.'},{title:'On vous montre le plan.',body:'En mots simples : voici le problème, voici la solution, voici le temps et l’argent que vous pouvez récupérer.'},{title:'On l’installe.',body:'Vous ne touchez à rien de technique. On fait l’ouvrage et on teste tout avant que vos employés s’en servent.'},{title:'On reste avec vous.',body:'On forme vos employés, on répond au téléphone, et on ajuste à mesure que vous grandissez.'}],
    whereLabel:'OÙ ON PEUT VOUS AIDER', whereTitle:'Votre entreprise.\nToutes ses possibilités.',whereIntro:'N’importe quel département. Si ça vous fait perdre du temps, on regarde comment le simplifier.',
    services:[{title:'Ventes',body:'Chaque appel, courriel et message se rend à la bonne personne. Les suivis sont faits, et vos clients potentiels ne sont plus oubliés.'},{title:'Marketing',body:'Faire entrer des clients de façon régulière au lieu d’espérer le bouche-à-oreille, et savoir exactement ce qui fonctionne.'},{title:'Bureau et administration',body:'Factures, soumissions, classement, entrée de données et horaires gérés en arrière-plan.'},{title:'Service à la clientèle',body:'Vos clients ont une réponse à 21 h un dimanche. Les vraies questions se rendent quand même à vos employés.'},{title:'Opérations',body:'La routine quotidienne roule toute seule, pour qu’une journée de maladie n’arrête pas l’entreprise.'},{title:'Embauche et personnel',body:'Organiser les candidatures et faciliter la formation des nouveaux sans y passer la semaine. Votre équipe garde les décisions.'},{title:'Vos chiffres',body:'Un seul écran simple : ventes, dépenses, et ce qui demande votre attention aujourd’hui.'},{title:'Sécurité et sauvegardes',body:'Vos fichiers et les informations de vos clients gardés en sécurité, avec des vérifications automatiques.'}],
    resultsTitle:'Ce que ça donne, concrètement.', results:['Des heures rendues à votre équipe chaque semaine','Moins d’appels manqués et de clients perdus','Des décisions basées sur de vrais chiffres','Des employés qui font le travail qu’ils aiment'],
    faqLabel:'PARLONS SIMPLEMENT',faqTitle:'De vraies questions.\nDes réponses claires.',
    faqs:[{title:'Je ne suis pas bon avec la technologie. Est-ce que c’est pour moi?',body:'Oui. C’est exactement pour vous. Vous n’avez rien à apprendre de compliqué. On choisit des outils simples, on vous les explique et on accompagne votre équipe.'},{title:'Est-ce que je dois changer mes systèmes actuels?',body:'Presque jamais. On travaille avec ce que vous avez déjà et on branche les morceaux ensemble.'},{title:'Combien ça coûte?',body:'La première rencontre est gratuite. Ensuite, on vous présente un plan et un prix adaptés à votre situation, avant de commencer.'},{title:'Et si ça ne marche pas pour mon entreprise?',body:'Le premier échange sert justement à voir où on peut vous aider. On regarde vos besoins et les limites des outils avant de vous proposer une solution.'},{title:'Mes données sont-elles en sécurité?',body:'On examine les accès, les outils et les sauvegardes avec vous. Les mesures à mettre en place dépendent des informations que votre entreprise utilise.'}],
    contactLabel:'LA SUITE COMMENCE ICI',contactTitle:'Et si vous retrouviez\nle temps d’avancer?',contactBody:'Commençons par une simple conversation. Aucun engagement, aucun mot compliqué, aucune pression.', booking:'Voir les disponibilités de Jason',bookingNote:'La réservation s’ouvre sur notre site actuel.', footer:'De la technologie simple qui redonne du temps aux propriétaires d’entreprise.',rights:'Tous droits réservés.',motion:'Animations',menu:'Menu'
  },
  en: {
    nav:['What we do','How it works','Where we help','Questions'],eyebrow:'Artificial intelligence. Real common sense.',headline:['FEWER TASKS.','MORE TIME.','MORE POSSIBILITIES.'],intro:'We optimize your business to help you save time and money.',heroBody:'We find what slows you down and install simple tools that take care of the tedious work. Your employees keep their jobs. They get their time back.',call:'Book a free call',discover:'See how it works',reassurance:'No technical knowledge needed. Across Canada, remotely or on site.',
    metrics:[{title:'Your team',body:'Still at the heart of your business'},{title:'Less busywork',body:'More room for meaningful work'},{title:'Free first call',body:'Let’s see how we can help'},{title:'Across Canada',body:'Remotely or on site'}],
    painLabel:'SOUND FAMILIAR?',painTitle:'AI is complex.\nYour workday shouldn’t be.',painIntro:'You don’t need to understand artificial intelligence. You want your departments to run better without becoming an IT expert.',
    pains:[{title:'“We keep answering the same emails.”',body:'We set up a system that answers right away and directs the cases that need attention to a person.'},{title:'“I see my numbers too late.”',body:'We build a simple view of what is happening in your business today, not last month.'},{title:'“My best people are stuck doing paperwork.”',body:'We take the paperwork off their desks so they can do the work you hired them for.'},{title:'“I’m worried it will be complicated.”',body:'You handle none of the technical work. We install it, train your people, and stay available afterward.'}],
    humanLabel:'TECHNOLOGY THAT WORKS FOR PEOPLE',humanTitle:'Same team.\nFresh momentum.',humanBody:['We’re not here to replace your employees. We’re here to give them their time back.','Copying information, chasing invoices, filling in the same form for the hundredth time: that’s the work we give to AI.','Your people can focus on what AI can’t do: talking to customers, making decisions, growing the business. Same team, more done, less burnout.'],quote:'“If someone has done it by hand for 20 years, the person isn’t the problem. The task is.”',
    howLabel:'HOW IT WORKS',howTitle:'Four steps.\nNo surprises.',steps:[{title:'We listen.',body:'We spend time with your business to find what really slows you down. This step is free.'},{title:'We show you the plan.',body:'In plain language: the problem, the solution, and the time and money you could save.'},{title:'We install it.',body:'We do the technical work and test everything before your employees start using it.'},{title:'We stay with you.',body:'We train your team, answer the phone, and adjust as your business grows.'}],
    whereLabel:'WHERE WE CAN HELP',whereTitle:'Your business.\nAll its possibilities.',whereIntro:'Any department. If it’s costing you time, let’s see how to simplify it.',services:[{title:'Sales',body:'Every call, email and message reaches the right person. Follow-ups happen, and potential customers are remembered.'},{title:'Marketing',body:'Bring in customers regularly instead of relying on word of mouth, and understand what works.'},{title:'Office and administration',body:'Invoices, quotes, filing, data entry and scheduling handled in the background.'},{title:'Customer service',body:'Your customers get an answer at 9 pm on a Sunday. Questions that need a person still reach your team.'},{title:'Operations',body:'Daily routines keep moving, so one sick day doesn’t stop the business.'},{title:'Hiring and people',body:'Organize applications and simplify onboarding. Your team stays in charge of decisions.'},{title:'Your numbers',body:'One simple view of sales, spending, and what needs your attention today.'},{title:'Security and backups',body:'Keep your files and customer information protected, with automatic checks.'}],
    resultsTitle:'What it means in practice.',results:['Hours back for your team every week','Fewer missed calls and lost customers','Decisions based on real numbers','Employees doing the work they enjoy'],
    faqLabel:'LET’S KEEP IT SIMPLE',faqTitle:'Real questions.\nClear answers.',faqs:[{title:'I’m not good with technology. Is this for me?',body:'Yes. We choose simple tools, explain how they work, and support your team.'},{title:'Do I have to replace my current systems?',body:'Almost never. We work with what you already have and connect the pieces.'},{title:'How much does it cost?',body:'The first meeting is free. Then we present a plan and a price for your needs before work begins.'},{title:'What if it doesn’t work for my business?',body:'Our first conversation is about finding where we can help. We look at your needs and the limits of the tools before proposing a solution.'},{title:'Is my data safe?',body:'We review access, tools and backups with you. The right measures depend on the information your business uses.'}],contactLabel:'YOUR NEXT CHAPTER',contactTitle:'What if you had\ntime to move forward?',contactBody:'Let’s start with a simple conversation. No commitment, no technical jargon, no pressure.',booking:'See Jason’s availability',bookingNote:'Booking opens on our current website.',footer:'Simple technology that gives business owners their time back.',rights:'All rights reserved.',motion:'Animations',menu:'Menu'
  }
};
